version: '3.3'

services:
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - .:/app
      - /app/node_modules   # Exclude node_modules from being mounted
    ports:
      - "4200:4200"
    environment:
      - DEBUG=1
    restart: always

  
